package com.atul.banking.util;

import com.atul.banking.entity.Customer;
import com.lowagie.text.*;
import com.lowagie.text.pdf.*;

import java.awt.Color;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;

public class CustomerReportPdfGenerator {

    public static ByteArrayInputStream generate(List<Customer> customers) {

        Document document = new Document(PageSize.A4.rotate());

        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {

            PdfWriter.getInstance(document, out);

            document.open();

            Font titleFont =
                    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20);

            Font headerFont =
                    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11);

            Font bodyFont =
                    FontFactory.getFont(FontFactory.HELVETICA, 10);

            Paragraph title =
                    new Paragraph("ENTERPRISE BANK", titleFont);

            title.setAlignment(Element.ALIGN_CENTER);

            document.add(title);

            Paragraph subTitle =
                    new Paragraph("Customer Report", headerFont);

            subTitle.setAlignment(Element.ALIGN_CENTER);

            document.add(subTitle);

            document.add(new Paragraph(" "));

            PdfPTable table = new PdfPTable(7);

            table.setWidthPercentage(100);

            table.setWidths(new float[]{
                    1.2f,
                    3f,
                    3f,
                    2.3f,
                    2.8f,
                    1.5f,
                    2f
            });

            addHeader(table, "ID");
            addHeader(table, "Full Name");
            addHeader(table, "Email");
            addHeader(table, "Mobile");
            addHeader(table, "Account No");
            addHeader(table, "Status");
            addHeader(table, "Balance");

            for (Customer customer : customers) {

                table.addCell(value(customer.getId()));

                table.addCell(value(customer.getFullName()));

                table.addCell(value(customer.getEmail()));

                table.addCell(value(customer.getMobile()));

                table.addCell(value(customer.getAccountNumber()));

                table.addCell(customer.isActive()
                        ? "ACTIVE"
                        : "BLOCKED");

                table.addCell("₹ " + customer.getBalance());
            }

            document.add(table);

            document.add(new Paragraph(" "));

            Paragraph footer =
                    new Paragraph(
                            "Generated by Enterprise Banking System",
                            bodyFont
                    );

            footer.setAlignment(Element.ALIGN_CENTER);

            document.add(footer);

            document.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

        return new ByteArrayInputStream(out.toByteArray());
    }

    private static void addHeader(PdfPTable table, String text) {

        PdfPCell cell = new PdfPCell(new Phrase(text));

        cell.setHorizontalAlignment(Element.ALIGN_CENTER);

        cell.setBackgroundColor(Color.LIGHT_GRAY);

        table.addCell(cell);
    }

    private static String value(Object value) {

        return value == null ? "" : value.toString();
    }

}